apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: voting-app
  labels:
    app: result
spec:
  type: LoadBalancer   # ✅ correct (external access)
  selector:
    app: result
  ports:
  - name: http
    port: 8081
    targetPort: 80